// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vbthggsqpdupfrwdhpvy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZidGhnZ3NxcGR1cGZyd2RocHZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2MjkyMDYsImV4cCI6MjA2MjIwNTIwNn0.qF2P40q_Qe2VeSGZ-vn-6Pa6NJ4eH4rXN_sE-OVYy6E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);